/**
 * Design tokens copied verbatim from stitch_docket_legal_workspace/docket/DESIGN.md
 * and every screen's inline tailwind.config script (they are byte-identical
 * across all 20 Stitch mockups). Keep this file as the single source of truth —
 * do not hand-tune individual values; if a screen needs something new, add it
 * here so every screen stays consistent.
 */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#131c27",
        "primary-fixed-dim": "#bec7d6",
        "surface-tint": "#565f6c",
        "on-surface-variant": "#44474b",
        "secondary-container": "#fdd7a4",
        "surface-container-high": "#ede7de",
        "surface-container-highest": "#e8e2d9",
        "on-tertiary-fixed": "#1b1c1a",
        "on-secondary-fixed": "#291800",
        "on-secondary-container": "#785c33",
        background: "#fff8ef",
        "tertiary-fixed-dim": "#c8c6c4",
        "secondary-fixed-dim": "#e5c18f",
        primary: "#07101a",
        "primary-container": "#1c2530",
        "on-surface": "#1d1b16",
        "surface-variant": "#e8e2d9",
        "surface-container-low": "#f9f3ea",
        "on-background": "#1d1b16",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffddb1",
        secondary: "#755a31",
        outline: "#75777c",
        "inverse-on-surface": "#f6f0e7",
        "on-tertiary-fixed-variant": "#474745",
        tertiary: "#0e0f0e",
        "on-primary-container": "#838c9a",
        "outline-variant": "#c5c6cc",
        surface: "#fff8ef",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#5b421c",
        "on-primary-fixed-variant": "#3e4754",
        "on-tertiary": "#ffffff",
        "surface-container": "#f3ede4",
        "surface-dim": "#dfd9d0",
        "tertiary-container": "#242423",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#fff8ef",
        "inverse-surface": "#33302a",
        "on-tertiary-container": "#8c8b89",
        error: "#ba1a1a",
        "tertiary-fixed": "#e4e2df",
        "inverse-primary": "#bec7d6",
        "primary-fixed": "#dae3f2",
        // Semantic additions (not in the base M3 token set, needed for status
        // pills/diffs across screens: Draft=amber, In Review=blue, Final=emerald,
        // Blocked/Failed=oxblood-error, Viki accent stays `secondary` brass).
        success: "#2F6F5B",
        "success-container": "#DCEEE7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "32px",
        unit: "4px",
        "margin-page": "48px",
        gutter: "24px",
        "stack-sm": "8px",
        "container-max-width": "1440px",
        "stack-md": "16px",
      },
      maxWidth: {
        "container-max-width": "1440px",
      },
      fontFamily: {
        "headline-lg": ["Newsreader", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-display": ["Newsreader", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        serif: ["Newsreader", "serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "1.2", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
